# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Customer2.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Customer2.proto',
  package='com.polarsparc.protobuf3.modular',
  syntax='proto3',
  serialized_options=_b('B\014CustomerInfoP\001'),
  serialized_pb=_b('\n\x0f\x43ustomer2.proto\x12 com.polarsparc.protobuf3.modular\"Z\n\x0cPhoneNumber2\x12\x0e\n\x06number\x18\x01 \x01(\t\x12:\n\x04type\x18\x02 \x01(\x0e\x32,.com.polarsparc.protobuf3.modular.PhoneType2\"\x93\x01\n\tCustomer2\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x10\n\x08\x65mail_id\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12@\n\x08phone_no\x18\x05 \x03(\x0b\x32..com.polarsparc.protobuf3.modular.PhoneNumber2*E\n\nPhoneType2\x12\x0e\n\nPT_UNKNOWN\x10\x00\x12\x0b\n\x07PT_HOME\x10\x01\x12\r\n\tPT_MOBILE\x10\x02\x12\x0b\n\x07PT_WORK\x10\x03\x42\x10\x42\x0c\x43ustomerInfoP\x01\x62\x06proto3')
)

_PHONETYPE2 = _descriptor.EnumDescriptor(
  name='PhoneType2',
  full_name='com.polarsparc.protobuf3.modular.PhoneType2',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PT_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PT_HOME', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PT_MOBILE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PT_WORK', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=295,
  serialized_end=364,
)
_sym_db.RegisterEnumDescriptor(_PHONETYPE2)

PhoneType2 = enum_type_wrapper.EnumTypeWrapper(_PHONETYPE2)
PT_UNKNOWN = 0
PT_HOME = 1
PT_MOBILE = 2
PT_WORK = 3



_PHONENUMBER2 = _descriptor.Descriptor(
  name='PhoneNumber2',
  full_name='com.polarsparc.protobuf3.modular.PhoneNumber2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='com.polarsparc.protobuf3.modular.PhoneNumber2.number', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.polarsparc.protobuf3.modular.PhoneNumber2.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=143,
)


_CUSTOMER2 = _descriptor.Descriptor(
  name='Customer2',
  full_name='com.polarsparc.protobuf3.modular.Customer2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='com.polarsparc.protobuf3.modular.Customer2.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='com.polarsparc.protobuf3.modular.Customer2.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email_id', full_name='com.polarsparc.protobuf3.modular.Customer2.email_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='com.polarsparc.protobuf3.modular.Customer2.age', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='phone_no', full_name='com.polarsparc.protobuf3.modular.Customer2.phone_no', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=293,
)

_PHONENUMBER2.fields_by_name['type'].enum_type = _PHONETYPE2
_CUSTOMER2.fields_by_name['phone_no'].message_type = _PHONENUMBER2
DESCRIPTOR.message_types_by_name['PhoneNumber2'] = _PHONENUMBER2
DESCRIPTOR.message_types_by_name['Customer2'] = _CUSTOMER2
DESCRIPTOR.enum_types_by_name['PhoneType2'] = _PHONETYPE2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhoneNumber2 = _reflection.GeneratedProtocolMessageType('PhoneNumber2', (_message.Message,), dict(
  DESCRIPTOR = _PHONENUMBER2,
  __module__ = 'Customer2_pb2'
  # @@protoc_insertion_point(class_scope:com.polarsparc.protobuf3.modular.PhoneNumber2)
  ))
_sym_db.RegisterMessage(PhoneNumber2)

Customer2 = _reflection.GeneratedProtocolMessageType('Customer2', (_message.Message,), dict(
  DESCRIPTOR = _CUSTOMER2,
  __module__ = 'Customer2_pb2'
  # @@protoc_insertion_point(class_scope:com.polarsparc.protobuf3.modular.Customer2)
  ))
_sym_db.RegisterMessage(Customer2)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
